version: '3.8'

services:
  ms-translate:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-translate:latest
    container_name: ms-translate
    ports:
      - "8080:8080"
    environment:
      # Spring Profiles
      SPRING_PROFILES_ACTIVE: docker
      
      # Redis Configuration
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      
      # AWS Configuration (LocalStack)
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_OVERRIDE: http://localstack:4566
      
      # Application Configuration
      LOGGING_LEVEL_COM_TRANSLATION: DEBUG
      
      # JVM Options
      JAVA_OPTS: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=75.0
        -Xlog:gc*:file=/tmp/gc.log
    depends_on:
      redis:
        condition: service_healthy
      localstack:
        condition: service_healthy
    networks:
      - ms-translate-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: ms-translate-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - ms-translate-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: ms-translate-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      SERVICES: dynamodb,translate,bedrock
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - localstack-data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ms-translate-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  ms-translate-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  localstack-data:
    driver: local
