server:
  port: 8080

spring:
  application:
    name: translation-service
  redis:
    host: localhost
    port: 6379
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=1h

aws:
  region: us-east-1
  translate:
    enabled: true
  bedrock:
    enabled: true
  dynamodb:
    table-name: translation-dictionary

translation:
  cache:
    ttl: 86400
  pipeline:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      translationService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

logging:
  level:
    com.translation: DEBUG
    org.springframework: INFO
